name: deploy
on:
  push:
    branches:
      - dev
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout dev
    
    - name: Use Node.js 14.x  #使用nodejs 12.x版本
      uses: actions/setup-node@v1 
      with:
        node-version: '14.x'

    - name: Install and Build
      run: npm install && npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        folder: docs/.vuepress/dist
        branch: main